default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: teneo
  password: teneo

  migrations_paths:
    - <%= Teneo::DataModel.migrations_path %>
    - "db/migrate"

development:
  <<: *default
  database: teneo_dev

test:
  <<: *default
  database: teneo_test

production:
  <<: *default
  database: teneo